[2021-05-26 10:15:19,446] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Kuwait_DAG.to_Postgres 2021-05-26T10:11:08.134565+00:00 [queued]>
[2021-05-26 10:15:19,473] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Kuwait_DAG.to_Postgres 2021-05-26T10:11:08.134565+00:00 [queued]>
[2021-05-26 10:15:19,474] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-26 10:15:19,474] {taskinstance.py:1069} INFO - Starting attempt 2 of 2
[2021-05-26 10:15:19,475] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-26 10:15:19,494] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): to_Postgres> on 2021-05-26T10:11:08.134565+00:00
[2021-05-26 10:15:19,501] {standard_task_runner.py:52} INFO - Started process 112 to run task
[2021-05-26 10:15:19,506] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Kuwait_DAG', 'to_Postgres', '2021-05-26T10:11:08.134565+00:00', '--job-id', '23', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/covid_dag.py', '--cfg-path', '/tmp/tmp1e0k_t1l', '--error-file', '/tmp/tmpy71o8vt6']
[2021-05-26 10:15:19,507] {standard_task_runner.py:77} INFO - Job 23: Subtask to_Postgres
[2021-05-26 10:15:19,569] {logging_mixin.py:104} INFO - Running <TaskInstance: Kuwait_DAG.to_Postgres 2021-05-26T10:11:08.134565+00:00 [running]> on host 431e058b07b3
[2021-05-26 10:15:19,633] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=Kuwait_DAG
AIRFLOW_CTX_TASK_ID=to_Postgres
AIRFLOW_CTX_EXECUTION_DATE=2021-05-26T10:11:08.134565+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-26T10:11:08.134565+00:00
[2021-05-26 10:15:20,140] {python.py:118} INFO - Done. Returned value was: None
[2021-05-26 10:15:20,156] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=Kuwait_DAG, task_id=to_Postgres, execution_date=20210526T101108, start_date=20210526T101519, end_date=20210526T101520
[2021-05-26 10:15:20,195] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-26 10:15:20,244] {local_task_job.py:146} INFO - Task exited with return code 0
